# Generated by Django 4.0 on 2022-02-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_last_roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_roll_time', models.DateTimeField()),
                ('last_rolled_collection', models.TextField(max_length=400)),
                ('user', models.CharField(max_length=255)),
            ],
        ),
    ]
