# Generated by Django 4.0.2 on 2022-02-16 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick_car', '0002_alter_user_last_roll_last_rolled_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_last_roll',
            name='last_roll_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_last_roll',
            name='last_rolled_collection',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
