# Generated by Django 4.0.2 on 2022-02-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick_car', '0003_alter_user_last_roll_last_roll_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='car_part',
            fields=[
                ('id', models.PositiveIntegerField(editable=False, primary_key=True, serialize=False)),
                ('URI_address', models.TextField(max_length=1000)),
                ('locked', models.BooleanField(default=False)),
                ('locked_for', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
