# Generated by Django 4.0.2 on 2022-02-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pick_car', '0005_car_part_locked_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_last_roll',
            name='last_roll_time',
            field=models.FloatField(max_length=100),
        ),
    ]
